DELETE FROM books;
DELETE FROM publishers;
DELETE FROM book_genres;
DELETE FROM fav_genres;
DELETE FROM users;
DELETE FROM custom_list_element;
DELETE FROM custom_list_types;
DELETE FROM book_ratings;
DELETE FROM books;